#if !UNITY_WEBGL_RENDERER_ONLY
using System.Collections;                                                                                                                                                                                                                                                                                                                                               
using NUnit.Framework;                                                                                                                                                                                                                                                                                                                                                    
using UnityEngine;                                                                                                                                                                                                                                                                                                                                                        
using UnityEngine.TestTools;                                                                                                                                                                                                                                                                                                                                              
using System;                                                                                                                                                                                                                                                                                                                                                             
using System.Reflection;                                                                                                                                                                                                                                                                                                                                                  
using UnityEngine.Assemblies;                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                        
namespace UnityEngine.Rendering.Tests                                                                                                                                                                                                                                                                                                                                     
{                                                                                                                                                                                                                                                                                                                                                                       
    // Exercises the boundary logic of GRDExclusionReasonText.GetLabel / GetTooltip.                                                                                                                                                                                                                                                                                    
    // GRDExclusionReasonText lives in the UnityEditor assembly (internal visibility),                                                                                                                                                                                                                                                                                  
    // so all access goes through reflection — consistent with GRDProfilerCounterNamesTests.                                                                                                                                                                                                                                                                            
    [TestFixture]                                                                                                                                                                                                                                                                                                                                                       
    sealed class GRDExclusionReasonTextTests                                                                                                                                                                                                                                                                                                                            
    {                                                                                                                                                                                                                                                                                                                                                                   
        const string k_TypeName = "UnityEditor.Rendering.GRDExclusionReasonText";                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
        Type m_Type;                                                                                                                                                                                                                                                                                                                                                    
        string[] m_Labels;                                                                                                                                                                                                                                                                                                                                              
        string[] m_Tooltips;                                                                                                                                                                                                                                                                                                                                            
        MethodInfo m_GetLabel;                                                                                                                                                                                                                                                                                                                                          
        MethodInfo m_GetTooltip;                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                        
        [SetUp]                                                                                                                                                                                                                                                                                                                                                         
        public void SetUp()                                                                                                                                                                                                                                                                                                                                             
        {                                                                                                                                                                                                                                                                                                                                                               
            m_Type = ResolveEditorType(k_TypeName);                                                                                                                                                                                                                                                                                                                     
            Assert.That(m_Type, Is.Not.Null,                                                                                                                                                                                                                                                                                                                            
                $"{k_TypeName} not found in any loaded assembly. " +                                                                                                                                                                                                                                                                                                    
                "If the type moved, update k_TypeName in this test.");                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                        
            m_Labels   = GetStringArray(m_Type, "k_Labels");                                                                                                                                                                                                                                                                                                            
            m_Tooltips = GetStringArray(m_Type, "k_Tooltips");                                                                                                                                                                                                                                                                                                          
            m_GetLabel   = m_Type.GetMethod("GetLabel",   BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);                                                                                                                                                                                                                                          
            m_GetTooltip = m_Type.GetMethod("GetTooltip", BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                        
            Assert.That(m_GetLabel,   Is.Not.Null, "GetLabel method not found via reflection.");                                                                                                                                                                                                                                                                        
            Assert.That(m_GetTooltip, Is.Not.Null, "GetTooltip method not found via reflection.");                                                                                                                                                                                                                                                                      
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenReasonIndexZero_WhenGetLabelCalled_ThenReturnsUnknownFallback()                                                                                                                                                                                                                                                                                
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            const int reason = 0; // None — k_Labels[0] is null; condition (reason > 0) is false                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var label = (string)m_GetLabel.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(label, Is.EqualTo("Unknown exclusion reason"),                                                                                                                                                                                                                                                                                                  
                "Index 0 (None) must fall through to the fallback label.");                                                                                                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenNegativeReasonIndex_WhenGetLabelCalled_ThenReturnsUnknownFallback()                                                                                                                                                                                                                                                                            
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            const int reason = -1;                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var label = (string)m_GetLabel.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(label, Is.EqualTo("Unknown exclusion reason"),                                                                                                                                                                                                                                                                                                  
                "Negative index must fall through to the fallback label.");                                                                                                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenOutOfBoundsReasonIndex_WhenGetLabelCalled_ThenReturnsUnknownFallback()                                                                                                                                                                                                                                                                         
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            int reason = m_Labels.Length; // one past the last valid entry                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var label = (string)m_GetLabel.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(label, Is.EqualTo("Unknown exclusion reason"),                                                                                                                                                                                                                                                                                                  
                "An index equal to array length must fall through to the fallback label.");                                                                                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenFirstValidReasonIndex_WhenGetLabelCalled_ThenReturnsSameLabelAsArray()                                                                                                                                                                                                                                                                         
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            const int reason = 1; // index 1 is the first real (non-None) exclusion reason                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var label = (string)m_GetLabel.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(label, Is.EqualTo(m_Labels[1]),                                                                                                                                                                                                                                                                                                                 
                "First valid reason index must return the corresponding k_Labels entry.");                                                                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenLastValidReasonIndex_WhenGetLabelCalled_ThenReturnsSameLabelAsArray()                                                                                                                                                                                                                                                                          
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            int reason = m_Labels.Length - 1;                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var label = (string)m_GetLabel.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(label, Is.EqualTo(m_Labels[reason]),                                                                                                                                                                                                                                                                                                            
                "Last valid reason index must return the corresponding k_Labels entry.");                                                                                                                                                                                                                                                                               
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenReasonIndexZero_WhenGetTooltipCalled_ThenReturnsEmptyString()                                                                                                                                                                                                                                                                                  
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            const int reason = 0;                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var tooltip = (string)m_GetTooltip.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(tooltip, Is.Empty,                                                                                                                                                                                                                                                                                                                              
                "Index 0 (None) must return empty string for tooltip.");                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenNegativeReasonIndex_WhenGetTooltipCalled_ThenReturnsEmptyString()                                                                                                                                                                                                                                                                              
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            const int reason = -1;                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var tooltip = (string)m_GetTooltip.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(tooltip, Is.Empty,                                                                                                                                                                                                                                                                                                                              
                "Negative index must return empty string for tooltip.");                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenOutOfBoundsReasonIndex_WhenGetTooltipCalled_ThenReturnsEmptyString()                                                                                                                                                                                                                                                                           
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            int reason = m_Tooltips.Length;                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var tooltip = (string)m_GetTooltip.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(tooltip, Is.Empty,                                                                                                                                                                                                                                                                                                                              
                "An index equal to array length must return empty string for tooltip.");                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenFirstValidReasonIndex_WhenGetTooltipCalled_ThenReturnsSameTooltipAsArray()                                                                                                                                                                                                                                                                     
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            const int reason = 1;                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var tooltip = (string)m_GetTooltip.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(tooltip, Is.EqualTo(m_Tooltips[1]),                                                                                                                                                                                                                                                                                                             
                "First valid reason index must return the corresponding k_Tooltips entry.");                                                                                                                                                                                                                                                                            
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenLastValidReasonIndex_WhenGetTooltipCalled_ThenReturnsSameTooltipAsArray()                                                                                                                                                                                                                                                                      
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            int reason = m_Tooltips.Length - 1;                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            var tooltip = (string)m_GetTooltip.Invoke(null, new object[] { reason });                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(tooltip, Is.EqualTo(m_Tooltips[reason]),                                                                                                                                                                                                                                                                                                        
                "Last valid reason index must return the corresponding k_Tooltips entry.");                                                                                                                                                                                                                                                                             
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        [Test]                                                                                                                                                                                                                                                                                                                                                          
        public void GivenReasonTextType_WhenReasonCountRead_ThenEqualsLabelsArrayLength()                                                                                                                                                                                                                                                                               
        {                                                                                                                                                                                                                                                                                                                                                               
            // ARRANGE                                                                                                                                                                                                                                                                                                                                                  
            var prop = m_Type.GetProperty("ReasonCount",                                                                                                                                                                                                                                                                                                                
                BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);                                                                                                                                                                                                                                                                                    
            Assert.That(prop, Is.Not.Null, "ReasonCount property not found via reflection.");                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                        
            // ACT                                                                                                                                                                                                                                                                                                                                                      
            int reasonCount = (int)prop.GetValue(null);                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                        
            // ASSERT                                                                                                                                                                                                                                                                                                                                                   
            Assert.That(reasonCount, Is.EqualTo(m_Labels.Length),                                                                                                                                                                                                                                                                                                       
                "ReasonCount must equal k_Labels.Length so callers can iterate all entries.");                                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                        
        static Type ResolveEditorType(string fullName)                                                                                                                                                                                                                                                                                                                  
        {                                                                                                                                                                                                                                                                                                                                                               
            foreach (var asm in CurrentAssemblies.GetLoadedAssemblies())                                                                                                                                                                                                                                                                                                
            {                                                                                                                                                                                                                                                                                                                                                           
                var t = asm.GetType(fullName, throwOnError: false);                                                                                                                                                                                                                                                                                                     
                if (t != null) return t;                                                                                                                                                                                                                                                                                                                                
            }                                                                                                                                                                                                                                                                                                                                                           
            return null;                                                                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                        
        static string[] GetStringArray(Type t, string fieldName)                                                                                                                                                                                                                                                                                                        
        {                                                                                                                                                                                                                                                                                                                                                               
            var f = t.GetField(fieldName, BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);                                                                                                                                                                                                                                                          
            Assert.IsNotNull(f, $"{t.FullName}.{fieldName} not found via reflection.");                                                                                                                                                                                                                                                                                 
            return (string[])f.GetValue(null);                                                                                                                                                                                                                                                                                                                          
        }                                                                                                                                                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                                                                                                                                   
}
#endif                                             